version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2  # Optional: cache Maven dependencies
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # prevent host/node_modules overwrite
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
